### ISSUE TITLE
Please guide me https://stackoverflow.com/questions/57167639/multi-column-search-using-specifications-spring-data-jpa-within-associated-entit

### ISSUE THREAD

**Issue by ghost** [TeamWanari/Spring-Specification-Example#1]

**Comment by aBnormaLz** [comment]
I'm closing this issue, because it's unrelated to the repository. If you want, you can try to implement your code according to my blogpost. If you got stuck or have any more questions please let me know!

https://leaks.wanari.com/2018/01/23/awesome-spring-specification

**Comment by ghost** [comment]
Could you please upgrade this tutorial to use Spring Boot Version 2.1.6.RELEASE ?

**Comment by aBnormaLz** [comment]
What is the error you get in that version?
